set(folder_name ${TARGET_NAME}/example)
add_executable(lb_example lb_example.c)
target_link_libraries(lb_example PRIVATE TurboNet::LB TurboNet::CoroNet)
set_target_properties( lb_example PROPERTIES FOLDER ${folder_name})
add_executable(worker_example worker_example.c)
target_link_libraries(worker_example PRIVATE TurboNet::CoroNet)
set_target_properties( worker_example PROPERTIES FOLDER ${folder_name})
add_executable(lb_l7_example lb_l7_example.c)
target_link_libraries(lb_l7_example PRIVATE TurboNet::LB TurboNet::CoroNet)
set_target_properties( lb_l7_example PROPERTIES FOLDER ${folder_name})
add_executable(worker_l7_example worker_l7_example.c)
target_link_libraries(worker_l7_example PRIVATE TurboNet::CoroNet)
set_target_properties( worker_l7_example PROPERTIES FOLDER ${folder_name})
add_executable(lb_tlv_example lb_tlv_example.c)
target_link_libraries(lb_tlv_example PRIVATE TurboNet::LB TurboNet::CoroNet)
set_target_properties( lb_tlv_example PROPERTIES FOLDER ${folder_name})
add_executable(worker_tlv_example worker_tlv_example.c)
target_link_libraries(worker_tlv_example PRIVATE TurboNet::CoroNet)
set_target_properties( worker_tlv_example PROPERTIES FOLDER ${folder_name})