if(BUILD_TESTING)
  add_executable(test_salts_tcp_proxy test_salts_tcp_proxy.c)
  target_link_libraries(test_salts_tcp_proxy PRIVATE SaltsNet::TCPProxy Salts::Core Salts::TinyTest)
  if(WIN32)
    target_link_libraries(test_salts_tcp_proxy PRIVATE ws2_32)
  endif()
  add_test(NAME salts_tcp_proxy COMMAND test_salts_tcp_proxy)
  set_target_properties(test_salts_tcp_proxy PROPERTIES FOLDER tproxy/tests)
endif()

if(BUILD_BENCHMARKS)
  add_executable(benchmark_salts_tcp_proxy_sg benchmark_salts_tcp_proxy_sg.c)
  target_link_libraries(benchmark_salts_tcp_proxy_sg PRIVATE SaltsNet::TCPProxy Salts::Core Salts::TinyTest)
  if(WIN32)
    target_link_libraries(benchmark_salts_tcp_proxy_sg PRIVATE ws2_32)
  endif()
  add_test(NAME benchmark_salts_tcp_proxy_sg COMMAND benchmark_salts_tcp_proxy_sg)
  set_tests_properties(benchmark_salts_tcp_proxy_sg PROPERTIES LABELS benchmark TIMEOUT 120)
  set_target_properties(benchmark_salts_tcp_proxy_sg PROPERTIES FOLDER tproxy/benchmarks)
endif()
