// re2c --lang c
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "platform.h"
#include "ast.h"
#include "parser.h" // Generated by Lemon

// Lemon functions
void *Asn1ParseAlloc(void *(*mallocProc)(size_t));
void Asn1ParseFree(void *p, void (*freeProc)(void*));
void Asn1Parse(void *yyp, int yymajor, AstNode *yyminor, ParseState *state);

// Helper to pass tokens to lemon
void push_token(void *pParser, int tokenType, const char *start, const char *end, ParseState *state) {
    int len = end - start;
    char *text = (char*)malloc(len + 1);
    strncpy(text, start, len);
    text[len] = '\0';
    
    // Wrap textual tokens in an AST node so the parser receives consistent types
    AstNode *val = new_node(NODE_Identifier, text, NULL, NULL);
    free(text);
    
    Asn1Parse(pParser, tokenType, val, state);
}

void scan(const char *cursor) {
    // Use global parse state
    memset(&g_parse_state, 0, sizeof(g_parse_state));
    void *pParser = Asn1ParseAlloc(malloc);
    const char *marker;
    const char *token_start;

    // re2c variables
    const char *YYCURSOR = cursor;
    const char *YYMARKER;

    while (1) {
        token_start = YYCURSOR;
    /*!re2c
        re2c:define:YYCTYPE = char;
        re2c:yyfill:enable = 0;

        // Skip Whitespace
        [ \t\n\r]+ { continue; }

        // Skip ASN.1 Comments (-- ...)
        "--" [^\n]* [\n] { continue; }

        // Keywords
        "DEFINITIONS" { push_token(pParser, TK_KW_DEFINITIONS, token_start, YYCURSOR, &g_parse_state); continue; }
        "BEGIN"       { push_token(pParser, TK_KW_BEGIN, token_start, YYCURSOR, &g_parse_state); continue; }
        "END"         { push_token(pParser, TK_KW_END, token_start, YYCURSOR, &g_parse_state); continue; }
        "SEQUENCE"    { push_token(pParser, TK_KW_SEQUENCE, token_start, YYCURSOR, &g_parse_state); continue; }
        "SET"         { push_token(pParser, TK_KW_SET, token_start, YYCURSOR, &g_parse_state); continue; }
        "CHOICE"      { push_token(pParser, TK_KW_CHOICE, token_start, YYCURSOR, &g_parse_state); continue; }
        "OF"          { push_token(pParser, TK_KW_OF, token_start, YYCURSOR, &g_parse_state); continue; }
        "INTEGER"     { push_token(pParser, TK_KW_INTEGER, token_start, YYCURSOR, &g_parse_state); continue; }
        "BOOLEAN"     { push_token(pParser, TK_KW_BOOLEAN, token_start, YYCURSOR, &g_parse_state); continue; }
        "OCTET"       { push_token(pParser, TK_KW_OCTET, token_start, YYCURSOR, &g_parse_state); continue; }
        "BIT"         { push_token(pParser, TK_KW_BIT, token_start, YYCURSOR, &g_parse_state); continue; }
        "STRING"      { push_token(pParser, TK_KW_STRING, token_start, YYCURSOR, &g_parse_state); continue; }
        "NULL"        { push_token(pParser, TK_KW_NULL, token_start, YYCURSOR, &g_parse_state); continue; }

        // Punctuation
        "::="  { push_token(pParser, TK_KW_ASSIGN, token_start, YYCURSOR, &g_parse_state); continue; }
        "{"    { push_token(pParser, TK_LBRACE, token_start, YYCURSOR, &g_parse_state); continue; }
        "}"    { push_token(pParser, TK_RBRACE, token_start, YYCURSOR, &g_parse_state); continue; }
        ","    { push_token(pParser, TK_COMMA, token_start, YYCURSOR, &g_parse_state); continue; }

        // Identifiers (Start with char, contain chars, digits, hyphens)
        [a-zA-Z][a-zA-Z0-9-]* { 
            push_token(pParser, TK_IDENTIFIER, token_start, YYCURSOR, &g_parse_state); 
            continue; 
        }

        // End of Input
        "\000" { 
            Asn1Parse(pParser, 0, NULL, &g_parse_state); // 0 is EOF for Lemon
            break; 
        }

        // Catch-all
        * { printf("Unexpected character: %c\n", *token_start); break; }
    */
    }

    if (g_parse_state.root) {
        printf("--- AST DUMP ---\n");
        print_tree(g_parse_state.root, 0);
        // Don't free here - ownership transferred to caller
    }

    Asn1ParseFree(pParser, free);
}