#ifndef exprtk_TYPES_H
#define exprtk_TYPES_H

#include <stddef.h>
#include <stdint.h>
#include "arena_buffer.h"
#include "turbo_str_view.h"

// Token types (used by Lexer -> Parser)
// Note: Actual token IDs are generated by Lemon, but we might arguably not need this enum 
// if we only use Lemon's defines. However, for the lexer generic return or debug, it's useful.
// We will rely on Lemon generic integer for token IDs mostly.

typedef enum {
    exprtk_NODE_NUMBER,
    exprtk_NODE_VARIABLE,
    exprtk_NODE_BINARY_OP,
    exprtk_NODE_FUNCTION_CALL,
    exprtk_NODE_ASSIGNMENT,
    exprtk_NODE_IF,
    exprtk_NODE_WHILE,
    exprtk_NODE_FOR,
    exprtk_NODE_BLOCK,
    exprtk_NODE_FLOW,
    exprtk_NODE_STRING,
    exprtk_NODE_VECTOR,
    exprtk_NODE_INDEX,
    exprtk_NODE_SLICE,
    exprtk_NODE_FUNCTION_DEFINITION
} exprtk_node_type_t;

typedef struct exprtk_node_s exprtk_node_t;

struct exprtk_node_s {
    exprtk_node_type_t type;
    turbo_arena_t *arena;
    union {
        double number;
        struct {
            char *name;
        } variable;
        struct {
            int op; // Token ID
            exprtk_node_t *left;
            exprtk_node_t *right;
        } binary;
        struct {
            char *name;
            exprtk_node_t **args;
            size_t arg_count;
        } function;
        struct {
            char *name;
            exprtk_node_t *value; // For assignment: var := value
        } assignment;
        struct {
            exprtk_node_t *condition;
            exprtk_node_t *if_branch;
            exprtk_node_t *else_branch;
        } if_stmt;
        struct {
            exprtk_node_t *condition;
            exprtk_node_t *body;
        } while_loop;
        struct {
            exprtk_node_t *init;
            exprtk_node_t *condition;
            exprtk_node_t *post;
            exprtk_node_t *body;
        } for_loop;
        struct {
            exprtk_node_t **statements;
            size_t count;
        } block;
        struct {
            int type; // exprtk_TOKEN_BREAK, _CONTINUE, _RETURN
            exprtk_node_t *value; // for return
        } flow;
        struct {
            tstr_v value;
        } string;
        struct {
            exprtk_node_t **elements;
            size_t count;
        } vector;
        struct {
            exprtk_node_t *array;
            exprtk_node_t *index;
        } index_access;
        struct {
            exprtk_node_t *array;
            exprtk_node_t *start;
            exprtk_node_t *end;
        } slice;
        struct {
            char *name;
            char **arg_names;
            size_t arg_count;
            exprtk_node_t *body;
        } func_def;
    } data;
};

typedef struct {
    double *data;
    size_t size;
} exprtk_vector_t;

// Evaluation result type
typedef struct {
    enum { exprtk_VAL_NUMBER, exprtk_VAL_STRING, exprtk_VAL_VECTOR } type;
    union {
        double number;
        tstr_v string;
        exprtk_vector_t vector;
    } data;
} exprtk_value_t;

// Symbol Table / Environment
typedef struct exprtk_var_s {
    char *name;
    exprtk_value_t value;
    int is_constant; // 1 if read-only
    struct exprtk_var_s *next;
} exprtk_var_t;

typedef exprtk_value_t (*exprtk_native_fn)(size_t arg_count, exprtk_value_t *args, void *user_data);

typedef struct exprtk_func_s {
    char *name;
    int is_script;
    union {
        struct {
            exprtk_native_fn fn;
            void *user_data;
        } native;
        struct {
            char **arg_names;
            size_t arg_count;
            exprtk_node_t *body;
        } script;
    } data;
    struct exprtk_func_s *next;
} exprtk_func_t;

typedef enum {
    exprtk_FLOW_NORMAL,
    exprtk_FLOW_BREAK,
    exprtk_FLOW_CONTINUE,
    exprtk_FLOW_RETURN
} exprtk_flow_t;

typedef struct exprtk_env_s {
    exprtk_var_t *head;
    exprtk_func_t *funcs;
    exprtk_flow_t flow;
    exprtk_value_t return_value;
    struct exprtk_env_s *parent;

    // Safety Limits
    uint32_t max_recursion;
    uint32_t curr_recursion;
    uint32_t max_loop_iterations;
    uint32_t curr_loop_iterations;
    uint32_t max_nodes;      // Max nodes to evaluate per expression
    uint32_t curr_nodes;
    int aborted;             // Set to 1 if any safety limit is exceeded
    turbo_arena_t arena;     // For persistent data like script function bodies
} exprtk_env_t;

// Simple context for parser
typedef struct {
    exprtk_node_t *root;
    int error;
    char error_msg[256];
    turbo_arena_t *arena;
} exprtk_parse_ctx_t;

// Helper to free nodes
void exprtk_free_node(exprtk_node_t *node);
void exprtk_env_init(exprtk_env_t *env);
void exprtk_env_free(exprtk_env_t *env);
exprtk_value_t exprtk_env_get(exprtk_env_t *env, const char *name);
void exprtk_env_set(exprtk_env_t *env, const char *name, exprtk_value_t value);

// Token structure passed from Lexer to Parser
typedef struct {
    int type;       // Token ID (from Lemon)
    const char *start;
    size_t length;
    double num_value; // For numbers
} exprtk_token_t;

#endif // exprtk_TYPES_H

