ARG TURBONET_BUILD_BASE=turbonet_build_base
FROM ${TURBONET_BUILD_BASE}

ENV CMAKE_PREFIX_PATH=/opt/turbonet
ENV LD_LIBRARY_PATH=/opt/turbonet/lib

WORKDIR /src/turbonet

COPY . ./

RUN cmake --preset linux-release-user \
    -D BUILD_EXAMPLES=OFF \
    -D BUILD_TESTS=OFF \
    -D CMAKE_INSTALL_PREFIX=/opt/turbonet \
    && cmake --build --preset linux-release-user --target install
