ARG TURBONET_BUILD_BASE=turbonet_build_base
FROM ${TURBONET_BUILD_BASE}

ENV CMAKE_PREFIX_PATH=/opt/turbonet
ENV LD_LIBRARY_PATH=/opt/turbonet/lib

WORKDIR /src/turbonet

COPY . ./

RUN cmake --preset linux-sdk-package \
    && cmake --build --preset linux-sdk-package --target install
