add_executable(test_salts_lb test_salts_lb.c)
target_link_libraries(test_salts_lb PRIVATE SaltsNet::LB Salts::Core Salts::TinyTest)
if(WIN32)
  target_link_libraries(test_salts_lb PRIVATE ws2_32)
endif()
add_test(NAME salts_lb COMMAND test_salts_lb)
set_target_properties(test_salts_lb PROPERTIES FOLDER lb/tests)
