# - Find RE2C executable and provides macros to generate custom build rules
# The module defines the following variables:
#
#  RE2C_EXECUTABLE - path to the re2c program
#  RE2C_VERSION - version of re2c
#  RE2C_FOUND - true if the program was found
#
# If re2c is found, the module defines the macros:
#
#  RE2C_TARGET(<Name> <Re2cInp> <CodeOutput>
#              [COMPILE_FLAGS <string>])
#
# which will create a custom rule to generate a lexer. <Re2cInp> is
# the path to a RE2C file. <CodeOutput> is the name of the source file
# generated by re2c. If COMPILE_FLAGS option is specified, the next
# parameter is added in the re2c command line.
#
# The macro defines a set of variables:
#  RE2C_${Name}_DEFINED       - true is the macro ran successfully
#  RE2C_${Name}_INPUT         - The input source file, an alias for <Re2cInp>
#  RE2C_${Name}_OUTPUT_SOURCE - The source file generated by re2c
#  RE2C_${Name}_OUTPUTS       - The source file generated by re2c
#  RE2C_${Name}_COMPILE_FLAGS - Options used in the re2c command line
#
#  ====================================================================
#  Example:
#
#   find_package(RE2C) # or e.g.: find_package(RE2C 2.0 REQUIRED)
#   RE2C_TARGET(MyLexer lexer.re ${CMAKE_CURRENT_BINARY_DIR}/lexer.cpp)
#   add_executable(Foo main.cpp ${RE2C_MyLexer_OUTPUTS})
#  ====================================================================

find_program(RE2C_EXECUTABLE NAMES re2c DOC "path to the re2c executable")
mark_as_advanced(RE2C_EXECUTABLE)

if(RE2C_EXECUTABLE)

  execute_process(
    COMMAND ${RE2C_EXECUTABLE} --version
    OUTPUT_VARIABLE RE2C_version_output
    ERROR_VARIABLE RE2C_version_error
    RESULT_VARIABLE RE2C_version_result
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )

  if(${RE2C_version_result} EQUAL 0)
    string(REGEX REPLACE "^re2c ([0-9.]+) .*$" "\\1" RE2C_VERSION
                         "${RE2C_version_output}"
    )
  else()
    message(
      SEND_ERROR "Command \"${RE2C_EXECUTABLE} --version\" failed with output:
${RE2C_version_error}"
    )
  endif()

  #============================================================
  # RE2C_TARGET (public macro)
  #============================================================
  #
  macro(RE2C_TARGET Name Input Output)
    set(RE2C_TARGET_usage
        "RE2C_TARGET(<Name> <Input> <Output> [COMPILE_FLAGS <string>]"
    )

    if(${ARGC} GREATER 3)
      if(${ARGC} EQUAL 5)
        if("${ARGV3}" STREQUAL "COMPILE_FLAGS")
          set(RE2C_EXECUTABLE_opts "${ARGV4}")
          separate_arguments(RE2C_EXECUTABLE_opts)
        else()
          message(SEND_ERROR ${RE2C_TARGET_usage})
        endif()
      else()
        message(SEND_ERROR ${RE2C_TARGET_usage})
      endif()
    endif()

    # Generate the output file at configure time
    execute_process(
      COMMAND ${RE2C_EXECUTABLE} ${RE2C_EXECUTABLE_opts} -o ${Output} ${Input}
      WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
      RESULT_VARIABLE STATUS
      ERROR_QUIET
    )
    if(STATUS AND NOT STATUS EQUAL 0)
      message(STATUS "RE2C generation FAILED: ${STATUS}")
    else()
      message(STATUS "RE2C generation SUCCESS ")
    endif()
    # Add a custom command to regenerate the output if the input changes
    add_custom_command(
      OUTPUT ${Output}
      COMMAND ${CMAKE_COMMAND} -E remove -f ${Output}
      COMMAND ${RE2C_EXECUTABLE} ARGS ${RE2C_EXECUTABLE_opts} -o ${Output}
              ${Input}
      DEPENDS ${Input}
      COMMENT "[RE2C][${Name}] Generating lexer with RE2C ${RE2C_VERSION}"
      WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    )

    # Set variables for use in the calling CMakeLists.txt
    set(RE2C_${Name}_DEFINED TRUE)
    set(RE2C_${Name}_INPUT ${Input})
    set(RE2C_${Name}_OUTPUT_SOURCE ${Output})
    set(RE2C_${Name}_OUTPUTS ${Output})
    set(RE2C_${Name}_COMPILE_FLAGS ${RE2C_EXECUTABLE_opts})
  endmacro()

endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  RE2C REQUIRED_VARS RE2C_EXECUTABLE VERSION_VAR RE2C_VERSION
)
