/**
 * @file exprtk_grammar.h
 * @brief Public wrapper for generated grammar token definitions
 *
 * This file is a stable public interface that includes the generated
 * token definitions. External modules (like turbo_script JIT compiler)
 * should include this file instead of directly depending on the
 * generated exprtk_grammar_gen.h.
 *
 * The actual token definitions are generated by Lemon parser generator
 * from exprtk_grammar.y and placed in the build directory.
 */

#ifndef EXPRTK_GRAMMAR_H
#define EXPRTK_GRAMMAR_H

#ifdef __cplusplus
extern "C" {
#endif

/* Always include the generated token definitions */
#include "exprtk_grammar_gen.h"

#ifdef __cplusplus
}
#endif

#endif /* EXPRTK_GRAMMAR_H */
