#ifndef exprtk_TYPES_H
#define exprtk_TYPES_H

#include <stddef.h>
#include <stdint.h>
#include "arena_buffer.h"
#include "turbo_str_view.h"

// Token types (used by Lexer -> Parser)
// Note: Actual token IDs are generated by Lemon, but we might arguably not need this enum 
// if we only use Lemon's defines. However, for the lexer generic return or debug, it's useful.
// We will rely on Lemon generic integer for token IDs mostly.

typedef enum {
    exprtk_NODE_NUMBER,
    exprtk_NODE_VARIABLE,
    exprtk_NODE_BINARY_OP,
    exprtk_NODE_FUNCTION_CALL,
    exprtk_NODE_ASSIGNMENT,
    exprtk_NODE_IF,
    exprtk_NODE_WHILE,
    exprtk_NODE_FOR,
    exprtk_NODE_SPREAD,
    exprtk_NODE_BLOCK,
    exprtk_NODE_FLOW,
    exprtk_NODE_STRING,
    exprtk_NODE_VECTOR,
    exprtk_NODE_INDEX,
    exprtk_NODE_SLICE,
    exprtk_NODE_FUNCTION_DEFINITION,
    exprtk_NODE_MEMBER_CALL,
    exprtk_NODE_CONSTANT_DECL,
    exprtk_NODE_SWITCH,
    exprtk_NODE_DO_WHILE,
    exprtk_NODE_MAP_LITERAL,
    exprtk_NODE_MEMBER_ACCESS,
    exprtk_NODE_MEMBER_SET,
    exprtk_NODE_FOR_IN,
    exprtk_NODE_NULL,
    exprtk_NODE_TEMPLATE_STRING,
    exprtk_NODE_DESTRUCTURING_ASSIGNMENT,
    exprtk_NODE_REST_PARAMETER,
    exprtk_NODE_TRY_CATCH,
    exprtk_NODE_THROW,
    exprtk_NODE_FUNCTION_EXPRESSION
} exprtk_node_type_t;

typedef struct exprtk_node_s exprtk_node_t;

struct exprtk_node_s {
    exprtk_node_type_t type;
    turbo_arena_t *arena;
    int line;
    int column;
    int inferred_type;  // Type inference result: exprtk_VAL_* or -1 if unknown
    union {
        double number;
        struct {
            char *name;
        } variable;
        struct {
            int op; // Token ID
            exprtk_node_t *left;
            exprtk_node_t *right;
        } binary;
        struct {
            char *name;
            exprtk_node_t **args;
            size_t arg_count;
        } function;
        struct {
            char *name;
            exprtk_node_t *value; // For assignment: var := value
        } assignment;
        struct {
            exprtk_node_t *condition;
            exprtk_node_t *if_branch;
            exprtk_node_t *else_branch;
        } if_stmt;
        struct {
            exprtk_node_t *condition;
            exprtk_node_t *body;
        } while_loop;
        struct {
            exprtk_node_t *init;
            exprtk_node_t *condition;
            exprtk_node_t *post;
            exprtk_node_t *body;
        } for_loop;
        struct {
            exprtk_node_t **statements;
            size_t count;
        } block;
        struct {
            int type; // exprtk_TOKEN_BREAK, _CONTINUE, _RETURN
            exprtk_node_t *value; // for return
        } flow;
        struct {
            tstr_v value;
        } string;
        struct {
            exprtk_node_t **elements;
            size_t count;
        } vector;
        struct {
            exprtk_node_t *array;
            exprtk_node_t *index;
        } index_access;
        struct {
            exprtk_node_t *array;
            exprtk_node_t *start;
            exprtk_node_t *end;
        } slice;
        struct {
            char *name;
            exprtk_node_t **arg_params;
            size_t arg_count;
            exprtk_node_t *body;
        } func_def;
        struct {
            exprtk_node_t *object;
            char *method;
            exprtk_node_t **args;
            size_t arg_count;
        } member_call;
        struct {
            exprtk_node_t *value;
            exprtk_node_t **cases;       // format: [case_val1, body1, case_val2, body2, ...]
            size_t case_count;           // number of cases * 2 == length of cases array
            exprtk_node_t *default_case;
        } switch_stmt;
        struct {
            exprtk_node_t *body;
            exprtk_node_t *condition;
        } do_while;
        struct {
            char **keys;
            exprtk_node_t **values;
            size_t count;
        } map_literal;
        struct {
            exprtk_node_t *object;
            char *member;
        } member_access;
        struct {
            exprtk_node_t *object;
            char *member;
            exprtk_node_t *value;
        } member_set;
        struct {
            char *var_name;
            exprtk_node_t *collection;
            exprtk_node_t *body;
        } for_in;
        struct {
            char *template_str;
            size_t len;
        } template_string;
        struct {
            exprtk_node_t *child;
        } spread;
        struct {
            exprtk_node_t *targets; // exprtk_NODE_VECTOR or exprtk_NODE_MAP_LITERAL
            exprtk_node_t *value;
            int is_constant;
        } destructuring;
        struct {
            exprtk_node_t *try_body;
            char *catch_var;          // variable name for the caught error
            exprtk_node_t *catch_body;
        } try_catch;
        struct {
            exprtk_node_t *value;     // expression to throw
        } throw_stmt;
    } data;
};

typedef struct {
    double *data;
    size_t size;
} exprtk_vector_t;

// Forward declaration for map
struct exprtk_map_entry_s;
struct exprtk_map_s;

// Evaluation result type
typedef struct exprtk_value_s {
    enum { exprtk_VAL_NUMBER, exprtk_VAL_STRING, exprtk_VAL_VECTOR, exprtk_VAL_MAP, exprtk_VAL_NULL, exprtk_VAL_LIST, exprtk_VAL_FUNCTION } type;
    union {
        double number;
        tstr_v string;
        exprtk_vector_t vector;
        struct {
            void *htab;          // HTAB(exprtk_map_kv_t)* — O(1) lookup
        } map;
        struct {
            struct exprtk_value_s *items;
            size_t count;
            size_t capacity;
        } list;
        struct {
            exprtk_node_t **arg_params;      // parameter nodes
            size_t arg_count;
            exprtk_node_t *body;
            struct exprtk_env_s *closure_env; // captured scope
        } function;
    } data;
} exprtk_value_t;

// Map entry (key-value pair) — defined after exprtk_value_t
typedef struct exprtk_map_entry_s {
    char *key;
    exprtk_value_t value;
} exprtk_map_entry_t;

typedef exprtk_value_t (*exprtk_native_fn)(size_t arg_count, exprtk_value_t *args, void *user_data);

typedef struct exprtk_func_s {
    char *name;
    int is_script;
    union {
        struct {
            exprtk_native_fn fn;
            void *user_data;
        } native;
        struct {
            exprtk_node_t **arg_params;
            size_t arg_count;
            exprtk_node_t *body;
        } script;
    } data;
    struct exprtk_func_s *next;
} exprtk_func_t;

typedef enum {
    exprtk_FLOW_NORMAL,
    exprtk_FLOW_BREAK,
    exprtk_FLOW_CONTINUE,
    exprtk_FLOW_RETURN,
    exprtk_FLOW_THROW
} exprtk_flow_t;

typedef struct exprtk_module_s exprtk_module_t;

typedef struct exprtk_env_s {
    void *vars;                      // Hash table for variables (opaque pointer to HTAB(exprtk_var_entry_t)*)
    exprtk_func_t *funcs;
    exprtk_flow_t flow;
    exprtk_value_t return_value;
    struct exprtk_env_s *parent;

    // Per-env static modules (mounted via exprtk_env_add_module)
    const exprtk_module_t **modules;
    size_t module_count;

    // Sorted cache of all module entries (built on first call, O(log n) lookup)
    void  *mod_cache;           // exprtk_func_entry_t* sorted array (opaque)
    size_t mod_cache_count;

    // Safety Limits
    uint32_t max_recursion;
    uint32_t curr_recursion;
    uint32_t max_loop_iterations;
    uint32_t curr_loop_iterations;
    uint32_t max_nodes;      // Max nodes to evaluate per expression
    uint32_t curr_nodes;
    int aborted;             // Set to 1 if any safety limit is exceeded
    int last_line;           // Line of last evaluated node
    int last_column;         // Column of last evaluated node
    turbo_arena_t arena;     // For persistent data like script function bodies
    exprtk_value_t error_value; // Value thrown by throw statement
    struct exprtk_env_s *next_closure; // linked list of closure scopes to free

    // Error reporting (Phase 2)
    char error_msg[256];     // Last error message
    int error_line;          // Line where error occurred
    int error_column;        // Column where error occurred
} exprtk_env_t;

// Simple context for parser
typedef struct {
    exprtk_node_t *root;
    int error;
    char error_msg[256];
    turbo_arena_t *arena;
} exprtk_parse_ctx_t;

#ifdef __cplusplus
extern "C" {
#endif

// Helper to free nodes
void exprtk_free_node(exprtk_node_t *node);

// Token structure passed from Lexer to Parser
typedef struct {
    int type;       // Token ID (from Lemon)
    const char *start;
    size_t length;
    double num_value; // For numbers
    int line;
    int column;
} exprtk_token_t;

#ifdef __cplusplus
}
#endif

#endif // exprtk_TYPES_H

