/**
 * @file cookie_parser.h
 * @brief HTTP Cookie parser header with re2c lexer and lemon parser integration
 */

#ifndef COOKIE_PARSER_H
#define COOKIE_PARSER_H

#include <stddef.h>
#include <time.h>

#ifdef __cplusplus
extern "C" {
#endif

// Forward declarations
struct http_cookie_jar_s;

// Token types for cookie lexer
typedef enum {
  COOKIE_EOF = 0,
  COOKIE_DOMAIN,
  COOKIE_PATH,
  COOKIE_EXPIRES,
  COOKIE_MAX_AGE,
  COOKIE_SECURE,
  COOKIE_HTTPONLY,
  COOKIE_SAMESITE,
  COOKIE_EQUALS,
  COOKIE_SEMICOLON,
  COOKIE_COMMA,
  COOKIE_TOKEN,
  COOKIE_QUOTED_VALUE,
  COOKIE_DATE_VALUE,
  COOKIE_NUMBER,
  COOKIE_UNKNOWN
} cookie_token_type_t;

// Token structure
typedef struct {
  cookie_token_type_t type;
  char *text;
  size_t len;
} cookie_token_t;

// Lexer structure
typedef struct {
  const char *input;
  const char *cursor;
  const char *limit;
  const char *marker;
  const char *token_start;
  size_t token_len;
  char error[256];
} cookie_lexer_t;

// Cookie attribute types
typedef enum {
  ATTR_DOMAIN,
  ATTR_PATH,
  ATTR_EXPIRES,
  ATTR_MAX_AGE,
  ATTR_SECURE,
  ATTR_HTTPONLY,
  ATTR_SAMESITE
} cookie_attribute_type_t;

// Cookie attribute structure
typedef struct cookie_attribute_s {
  cookie_attribute_type_t type;
  char *value;
  struct cookie_attribute_s *next;
} cookie_attribute_t;

// Enhanced cookie structure
typedef struct http_cookie_s {
  char *name;
  char *value;
  char *domain;
  char *path;
  char *same_site;
  time_t expires;
  int max_age;
  int secure;
  int http_only;
  cookie_attribute_t *attributes;
  struct http_cookie_s *next;
} http_cookie_t;

// Parser context
typedef struct {
  http_cookie_t *result;
  int error;
  const char *error_message;
} cookie_parser_context_t;

// Lexer functions
void cookie_lexer_init(cookie_lexer_t *lexer, const char *input);
cookie_token_type_t cookie_lexer_next(cookie_lexer_t *lexer, cookie_token_t *token);
void cookie_token_free(cookie_token_t *token);
void cookie_lexer_cleanup(cookie_lexer_t *lexer);

// Parser functions (generated by lemon with %name CookieParse)
void *CookieParseAlloc(void *(*mallocProc)(size_t));
void CookieParse(void *yyp, int yymajor, cookie_token_t *yyminor, cookie_parser_context_t *ctx);
void CookieParseFree(void *p, void (*freeProc)(void *));

// High-level parsing function
http_cookie_t *parse_set_cookie_rfc(const char *set_cookie_value);

// Cookie utility functions
void http_cookie_free(http_cookie_t *cookie);
void cookie_attribute_free(cookie_attribute_t *attr);
void cookie_attribute_free_list(cookie_attribute_t *list);

// Cookie matching functions
int cookie_matches_request(http_cookie_t *cookie, const char *url);
int domain_matches(const char *host, const char *cookie_domain);
int path_matches(const char *request_path, const char *cookie_path);

// Cookie jar functions (enhanced)
char *build_cookie_header_rfc(struct http_cookie_jar_s *jar, const char *url);
void http_cookie_jar_add_parsed(struct http_cookie_jar_s *jar, http_cookie_t *cookie);
void http_cookie_jar_cleanup_expired(struct http_cookie_jar_s *jar);

// Enhanced cookie creation
http_cookie_t *http_cookie_create_normalized(const char *name, const char *value,
                                             const char *domain, const char *path);

#ifdef __cplusplus
}
#endif

#endif // COOKIE_PARSER_H